### ISSUE TITLE
Use with bootstrap4 theme?

### ISSUE THREAD

**Issue by hartwork** [jerinpetergeorge/django-simple-select2#3]
Hi!

I have been thinking about an easy and maintainable way to use django-simple-select2 with [select2-bootstrap4-theme](https://github.com/ttskch/select2-bootstrap4-theme) to blend into existing projects using Bootstrap 4. It seems to take two things:

1. getting the `.css` file into `.media` of the widget class and
2. passing `theme: "bootstrap4"` to the `.select2(...)` initialization.

For (1) inheriting from `AutocompleteMixin` and overriding `.media` should work. (2) seems more tricky. Replacing `autocomplete.js` altogether would not be too cool but https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/autocomplete.js does not seem to expose options to the outside so I don't see a way around it right now. Any ideas to achieve this in a more simple and more maintainable way?

Are you using Select2 theme `default`? Do you happen to have plans to ship support for bootstrap4 theming out of the box? 

Thanks and best, Sebastian

**Comment by erdseb** [comment]
@jerinpetergeorge what do you think?

**Comment by jerinpetergeorge** [comment]
SFLR;

> Are you using Select2 theme `default`?

Nop, the [**`admin-autocomplete`**](https://github.com/django/django/blob/ec5aa2161d8015a3fe57dcbbfe14200cd18f0a16/django/contrib/admin/widgets.py#L411), I presume.

So, I assume we have something called **`data-theme`** field which intakes the theme name and probably that will reduce a lot of works. 
@erdseb @hartwork

**Comment by jerinpetergeorge** [comment]
>Do you happen to have plans to ship support for bootstrap4 theming out of the box?

I wasn't thinking about it, but it will be nice. So, it is a **Yes** :smile: 

If the **`data-theme`** works fine, we should open settings variable or some attribute to manage the theme per widget or per project.

**Comment by hartwork** [comment]
Interesting find! I didn't find any code respecting the value in `data-theme` though. How does it make its way through to https://github.com/django/django/blob/ec5aa2161d8015a3fe57dcbbfe14200cd18f0a16/django/contrib/admin/static/admin/js/autocomplete.js#L15 ?

**Comment by jerinpetergeorge** [comment]
Checkout this select2 doc, [**Nested (subkey) options**](https://select2.org/configuration/data-attributes#nested-subkey-options).

Django adds extra attributes while building the widget and the _select2_ using it.

**Comment by hartwork** [comment]
I see — thanks! How shall we proceed?

**Comment by jerinpetergeorge** [comment]
Yep. Would you like to make a pull request?

**Comment by hartwork** [comment]
Sorry I didn't reply earlier. Let's see how for I get with a pull request, yes.
